# Generated by Django 6.0.3 on 2026-03-20 12:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articleimage_articlevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevideo',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
    ]
